version: '3.8'

services:
  photo-assistant:
    build: .
    ports:
      - "8501:8501"
    environment:
      - GOOGLE_CLOUD_VISION_API_KEY=${GOOGLE_CLOUD_VISION_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./static/uploads:/app/static/uploads
    restart: unless-stopped 